version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: devnotes
      POSTGRES_PASSWORD: devnotes
      POSTGRES_DB: devnotes
    ports:
      - "5422:5432"
    volumes:
      - devnotes-data:/var/lib/postgresql/data

volumes:
  devnotes-data:
